language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=ffmpeg-vaapi
    - DOCKER_CACHE_ARGS=""
    - CACHE_FROM_IMAGE="${DOCKER_REGISTRY}/${DOCKER_REGISTRY_REPO}/${IMAGE_NAME}:latest"
    - FINAL_IMAGE=${DOCKER_REGISTRY}/${DOCKER_REGISTRY_REPO}/${IMAGE_NAME}

before_install:
  - sudo apt-get install -y jq
  - sudo sed -i "s/\DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry=${DOCKER_REGISTRY} /g" /etc/default/docker
  - sudo service docker restart
  - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username ${DOCKER_REGISTRY_USERNAME} --password-stdin ${DOCKER_REGISTRY}

install:
  - if [[ "master" != "${TRAVIS_BRANCH}" ]]; then
                docker pull ${CACHE_FROM_IMAGE} || true;
                DOCKER_CACHE_ARGS="--cache-from ${CACHE_FROM_IMAGE}";
        fi

script:
  - set -e
  - docker build --compress ${DOCKER_CACHE_ARGS} --tag ${IMAGE_NAME}:build .
  - docker run --rm -t ${IMAGE_NAME}:build -buildconf
  - bash runtests.sh

after_success:
  - if [[ "master" == "${TRAVIS_BRANCH}" ]]; then 
      FINAL_IMAGE="${FINAL_IMAGE}:latest";
    else
      FINAL_IMAGE="${FINAL_IMAGE}:${TRAVIS_BRANCH}";
    fi
  - echo "Pushing to ${FINAL_IMAGE}"
  - docker tag ${IMAGE_NAME}:build ${FINAL_IMAGE}
  - docker push ${FINAL_IMAGE}

