language: minimal

services:
  - docker

env:
  matrix:
    - OS=centos
    - OS=alpine
  global:
    - IMAGE_NAME=ffmpeg-vaapi
    - DOCKER_CACHE_ARGS=""
    - CACHE_FROM_IMAGE="${DOCKER_REGISTRY}/${DOCKER_REGISTRY_REPO}/${IMAGE_NAME}:${OS}"
    - FINAL_IMAGE=${DOCKER_REGISTRY}/${DOCKER_REGISTRY_REPO}/${IMAGE_NAME}

before_install:
  - sudo apt-get install -y jq
  - sudo sed -i "s/\DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry=${DOCKER_REGISTRY} /g" /etc/default/docker
  - sudo service docker restart
  - echo ${DOCKER_REGISTRY_PASSWORD} | docker login --username ${DOCKER_REGISTRY_USERNAME} --password-stdin ${DOCKER_REGISTRY}

install:
  - if [[ "master" != "${TRAVIS_BRANCH}" ]]; then
                docker pull ${CACHE_FROM_IMAGE} || true;
                DOCKER_CACHE_ARGS="--cache-from ${CACHE_FROM_IMAGE}";
        fi

script:
  - docker build -f Dockerfile.${OS} --compress ${DOCKER_CACHE_ARGS} --tag ${IMAGE_NAME}:build .
  - docker run --rm -t ${IMAGE_NAME}:build -buildconf
  - bash runtests.sh

after_success:
  - if [[ "master" == "${TRAVIS_BRANCH}" ]]; then 
      export PUSH_IMAGE="${FINAL_IMAGE}:${OS}";
    else
      export PUSH_IMAGE="${FINAL_IMAGE}:${OS}-${TRAVIS_BRANCH}";
    fi
  - echo "Pushing to ${PUSH_IMAGE}"
  - docker tag ${IMAGE_NAME}:build ${PUSH_IMAGE}
  - docker push ${PUSH_IMAGE}
  - if [[ "master" == "${TRAVIS_BRANCH}" && "${OS}" == "centos" ]]; then
      docker tag ${IMAGE_NAME}:build ${FINAL_IMAGE}:latest;
      echo "Pushing to ${FINAL_IMAGE}:latest";
      docker push ${FINAL_IMAGE}:latest;
    fi

